### ISSUE TITLE
No way to override colours

### ISSUE THREAD

**Issue by rsking** [adospace/fluent-ui-xaml#6]
As the brushes are hard coded into the FabricUI, and all references to the brushes as via StaticResource, one cannot override the brush colours. I was trying to do this to get a dark mode, but was unable to change any of the colours.

**Comment by adospace** [comment]
I used StaticResource instead of DynamicResource for performance reasons: I like your approach, another way to do the more or less the same (adding a dark theme) but always using StaticResource would be like what I'm using in another library that I'm authoring ([https://github.com/adospace/fluent-ui-desktop](https://github.com/adospace/fluent-ui-desktop)).
I mean it's unlikely that the developer replaces a single color, more often he just wants to select a Light/Dark theme: swapping the dictionary of colors in the Application.Current.Resources should do the trick.
Something like this:

```
Application.Current.Resources.MergedDictionaries.Clear();
Application.Current.Resources.MergedDictionaries.Add(my them dictionary);
```

**Comment by adospace** [comment]
to further explain what I'm envisioning please take a look at this article: [https://michaelscodingspot.com/wpf-complete-guide-themes-skins/](https://michaelscodingspot.com/wpf-complete-guide-themes-skins/)
I'm using the same in [https://github.com/adospace/fluent-ui-desktop](https://github.com/adospace/fluent-ui-desktop)
